name: build_pipeline
   
on :
  workflow_call: 

     
jobs:
  build:
    runs-on: [self-hosted, linux, X64, research]
    steps:
      - name: Step 1 - Checkout Repository from GitHub      
        uses: actions/checkout@v2

      - name: Step 2 - Gradle wrapper version validation
        uses: gradle/wrapper-validation-action@v1
      
      - name: Step 3 - Use Java version 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
                
      - name: Step 4 - Granting permissions to gradlew file
        run: chmod +x ./gradlew
                  
      - name: Step 5 - Build with Gradle
        uses: gradle/gradle-build-action@v2.1.1
        with:
          arguments: build
          
      - name: Step 6 - Listing the build file name
        run: |
          ls '${{ github.workspace }}'/build/libs
          
      - name: Step 7 -  Retrieve version and name
        id: version         
        run: |
          echo "::set-output name=TAG_NAME::$(cat ${{ github.workspace }}/build.gradle |grep "version =" | grep -Eo '[0-9]\.[0-9]\.[0-9]')"
          echo "::set-output name=APP_NAME::$(cat ${{ github.workspace }}/settings.gradle |grep -oP "rootProject.name = '\K[^']+")"
        
      - name: Step 8 - Application name with version
        id: name_version
        run: |
          echo "::set-output name=APP_NAME_VERSION::${{ steps.version.outputs.APP_NAME }}-${{ steps.version.outputs.TAG_NAME }}"
          
      - name: step 9 - upload to jfrog
        run: |
          curl -H -X PUT "https://gunasekard.jfrog.io/artifactory/sample_artifact-gradle-dev/${{ steps.name_version.outputs.APP_NAME_VERSION }}.jar" -T '${{ github.workspace }}'/build/libs/${{ steps.name_version.outputs.APP_NAME_VERSION }}.jar
          

